# Generated by Django 5.0.3 on 2024-03-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='academyUsersCredentials',
            new_name='academy_Users_Credentials',
        ),
    ]
