# Generated by Django 5.0.3 on 2024-03-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_members_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_academicMember', models.CharField(max_length=32)),
                ('password_academicMember', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
