# Generated by Django 5.0.3 on 2024-03-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='estado_solicitud',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
