# Generated by Django 5.0.3 on 2024-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='estado_solicitud',
            field=models.CharField(default='Pendiente', max_length=200, null=True),
        ),
    ]
