# Generated by Django 5.0.3 on 2024-04-14 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.professor'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.professor'),
        ),
    ]
