# Generated by Django 5.0.3 on 2024-05-01 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notification_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceremonyactivity',
            name='ceremony',
        ),
        migrations.AddField(
            model_name='ceremony',
            name='ceremony_activities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.ceremonyactivity'),
        ),
    ]
