# Generated by Django 5.0.4 on 2024-04-19 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_event_profesor_alter_eventrequest_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='extra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.professor'),
        ),
    ]
