# Generated by Django 5.0.3 on 2024-04-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_event_profesor_alter_eventrequest_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.professor'),
        ),
    ]
