# Generated by Django 5.0.3 on 2024-03-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_eventrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequest',
            name='usuario',
        ),
    ]
