# Generated by Django 5.0.3 on 2024-05-01 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_ceremony_ceremony_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremonyactivity',
            name='ceremony',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceremony_activities', to='myapp.ceremony'),
        ),
    ]
