# Generated by Django 5.0.4 on 2024-05-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_ceremonyactivity_ceremony'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='descripcion',
            field=models.CharField(default='Reunion de inversionistas', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='titulo',
            field=models.CharField(default='Reunion de inversionista 2024-1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='descripcion',
            field=models.CharField(default='Taller para estudiantes de la rama de economia y negocios, apoyados en una empresa', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='titulo',
            field=models.CharField(default='Taller de finanzas', max_length=200),
            preserve_default=False,
        ),
    ]
