# Generated by Django 5.0.4 on 2024-04-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_event_extra_alter_eventrequest_extra_and_more'),
        ('myapp', '0004_event_estado_solicitud_alter_event_extra_and_more'),
        ('myapp', '0005_remove_notification_user'),
    ]

    operations = [
    ]
