# Generated by Django 5.0.2 on 2024-04-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_eventrequest_estado_solicitud'),
        ('myapp', '0006_eventrequest_extra'),
    ]

    operations = [
    ]
