# Generated by Django 5.0.4 on 2024-04-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_merge_20240427_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='extra',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='extra',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
