# Generated by Django 5.0.4 on 2024-04-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_event_estado_aimentacion_event_estado_extras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='estado_aimentacion',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='estado_extras',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='estado_transporte',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
    ]
